language: php

php:
  - 5.3

before_install:
  - git submodule update --init --recursive

before_script:
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp
  - mv ../ImageTable plugins/ImageTable
  - chmod -R 777 ../cakephp/app/tmp
  - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
  - echo "<?php
    class DATABASE_CONFIG {
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'database' => 'cakephp_test',
      'host' => '0.0.0.0',
      'login' => 'travis',
      'host' => '',
      'persistent' => false,
    );
    }" > ../cakephp/app/Config/database.php
 
script:
  - ./lib/Cake/Console/cake test ImageTable Controller/ImageController --stderr
  - ./lib/Cake/Console/cake test ImageTable Model/Image --stderr
  - ./lib/Cake/Console/cake test ImageTable Model/Behavior/UploadBehavior --stderr 
  - ./lib/Cake/Console/cake test ImageTable View/Helper/ImageTableHelper --stderr 